name: Long Usage
on:
  push:
    branches:
      - master
              
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
# ---------------------- Generate Release Tag ----------------------------
      - name: get system date
        run: |
          echo "::set-env name=CURRENTDATE::$(date)"
      - name: Replace Spaces with _
        id: regex
        uses: frabert/replace-string-action@v1.1
        with:
          # Regular expression pattern
          pattern: '[ :]'
          # The input string
          string: "${{env.CURRENTDATE}}"
          # What to replace with
          replace-with: "_"
          # Flags to use when matching
          flags: g # optional
          
# ---------------------- Checkout Code -----------------------------------
      - name: Checkout code
        uses: actions/checkout@v2
        
# ---------------------- Generate a Release ------------------------------
# See: pandoc_gh_actions.txt
# ---------------------- Convert all Files using Pandoc -----------------
      - name: install pandoc
        run: |
          sudo apt-get install texlive
          sudo apt-get install pandoc
          dpkg -L pandoc
          pandoc -v
      - name: convert all files
        run: |
          FILES= find ./ -regex ".*\.md"
          sudo mkdir ./outputs
          for f in $FILES
          do
            filename="${f%.*}"
            echo "Converting $f to $filename.pdf"
            pandoc $f -t pdf -o ./outputs/$filename.pdf
          done

# ---------------------- Add all Files to Release ------------------
      - name: Create Release and add all files
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.regex.outputs.replaced}}
          name: PDF Versions on ${{env.CURRENTDATE}}
          gzip: folders
          files: >
            outputs/
