name: Long Usage
on:
  push:
    branches:
      - master
              
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: get system date
        run: |
          echo "::set-env name=CURRENTDATE::$(date)"
      - name: Replace Spaces with _
        id: regex
        uses: frabert/replace-string-action@v1.1
        with:
          # Regular expression pattern
          pattern: '[ :]'
          # The input string
          string: "${{env.CURRENTDATE}}"
          # What to replace with
          replace-with: "_"
          # Flags to use when matching
          flags: g # optional
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.regex.outputs.replaced}}
          release_name: PDF Versions on ${{env.CURRENTDATE}}
          draft: false
          prerelease: false
      - name: install pandoc
        uses: docker://pandoc/latex:2.9

      - name: convert all files
        run: |
          $(FILES= sudo find ./ -regex ".*\.md"
          sudo mkdir ./outputs
          for f in $FILES
          do
            # extension="${f##*.}"
            filename="${f%.*}"
            echo "Converting $f to $filename.pdf"
            pandoc $f -t pdf -o ./outputs/$filename.pdf
          done)
      - name: Convert project # This would actually build your project, using zip for an example artifact
        uses: docker://pandoc/latex:2.9
        with:
          args: -s -o README.pdf ${{env.FILELIST}}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: outputs/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      
      
