name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:  
      - uses: maxheld83/pandoc@v0.1.0
        with:
          env: OUT_DIR = "public"
          args: |
            --standalone
            --output=public/index.html
            ~/README.md
