name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:  
      - uses: docker://pandoc/core:2.9
        with:
          args: '-s -o README.pdf README.md'
      
